version: '3'

services:
  admin:
    image: apache/dubbo-admin
    depends_on:
      - zoo1
      - zoo2
      - zoo3
    ports:
      - 8090:8080
    environment:
      - admin.registry.address=zookeeper://zoo1:2181,zoo2:2182,zoo3:2183
      - admin.config-center=zookeeper://zoo1:2181,zoo2:2182,zoo3:2183
      - admin.metadata-report.address=zookeeper://zoo1:2181,zoo2:2182,zoo3:2183
  zoo1:
    image: zookeeper:latest
    container_name: zk1
    restart: always
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zk1:2888:3888;2181 server.2=zk2:2888:3888;2181 server.3=zk3:2888:3888;2181
  zoo2:
    image: zookeeper:latest
    container_name: zk2
    restart: always
    ports:
      - "2182:2181"
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zk1:2888:3888;2181 server.2=zk2:2888:3888;2181 server.3=zk3:2888:3888;2181
    depends_on: 
      - zoo1
  zoo3:
    image: zookeeper:latest
    container_name: zk3
    restart: always
    ports:
      - "2183:2181"
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zk1:2888:3888;2181 server.2=zk2:2888:3888;2181 server.3=zk3:2888:3888;2181
    depends_on: 
      - zoo1

    
