version: '3'

services: 
  redis-master:
    image: redis
    restart: always
    container_name: redis-master
    command: redis-server --requirepass 123456
    ports:
      - 6378:6379
    volumes:
      - ./master_data:/data
  redis-slave1:
    image: redis
    restart: always
    container_name: redis-slave1
    command: redis-server --slaveof redis-master 6379 --requirepass 123456 --masterauth 123456 
    depends_on:
      - redis-master
    ports:
      - 6377:6379
    volumes:
      - ./slave1_data:/data
  redis-slave2:
    image: redis
    restart: always
    container_name: redis-slave2
    command: redis-server --slaveof redis-slave1 6379 --requirepass 123456 --masterauth 123456 
    depends_on:
      - redis-slave1
    ports:
      - 6376:6379
    volumes:
      - ./slave2_data:/data
  sentinel1:
    image: redis
    container_name: sentinel1
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    volumes:
      - "./sentinel/sentinel1.conf:/usr/local/etc/redis/sentinel.conf"
    depends_on:
      - redis-master
  sentinel2:
    image: redis
    container_name: sentinel2
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    volumes:
      - "./sentinel/sentinel2.conf:/usr/local/etc/redis/sentinel.conf"
    depends_on:
      - redis-master
  sentinel3:
    image: redis
    container_name: sentinel3
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    volumes:
      - "./sentinel/sentinel3.conf:/usr/local/etc/redis/sentinel.conf"
    depends_on:
      - redis-master

