version: '3'

services: 
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: always
    container_name: sqlserver
    ports:
      - 41433:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=password@123
    volumes:
      - ./mssql:/var/opt/mssql
