version: "3"
services:
  rabbitmq:
    image: "rabbitmq:latest"
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=root
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"
