version: "3"

services:
  es7:
    hostname: es7
    container_name: es7
    image: elasticsearch:7.3.0
    volumes:
      - "./logs:/usr/share/elasticsearch/logs:rw"
      - "./data:/usr/share/elasticsearch/data:rw"
      - "./plugins/ik:/usr/share/elasticsearch/plugins/ik:rw"
    restart: on-failure
    ports: 
      - "9200:9200"
      - "9300:9300"
    environment:
      cluster.name: elasticsearch
      discovery.type: single-node
    logging:
      driver: "json-file"
      options:
        max-size: "50m"


  kibana:
    image: kibana:7.3.0
    restart: on-failure
    container_name: kibana
    volumes:
       - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
       # - ./head/_site/app.js:/usr/src/app/_site/app.js       
       #  
    ports:
       - "5601:5601"           
    links:
       - es7

